global:
  scrape_interval: 10s  # Set the scrape interval to every 10 seconds. Default is every 1 minute.
  evaluation_interval: 10s  # Evaluate rules every 10 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: /actuator/prometheus # Application Prometheus endpoint
    scrape_interval: 5s
    static_configs:
      - targets: # Application host:port
          - host.docker.internal:8080

  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - node-exporter:9100
